import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { VisualHiveConfigSchema } from "@visual-hive/core";
import { buildSpecContent } from "../src/generator.js";
import { collectArtifacts } from "../src/artifactCollector.js";
import { waitForServerUrl } from "../src/serverManager.js";

const tempDirs: string[] = [];

afterEach(async () => {
  for (const dir of tempDirs.splice(0)) {
    await rm(dir, { recursive: true, force: true });
  }
});

describe("buildSpecContent", () => {
  it("includes expected selectors, routes, viewport usage, and mutation hook", () => {
    const config = VisualHiveConfigSchema.parse({
      project: { name: "sample", type: "react-vite", defaultBranch: "main" },
      targets: {
        localPreview: {
          kind: "url",
          url: "http://127.0.0.1:4173",
          prSafe: true,
          cost: "cheap"
        }
      },
      contracts: [
        {
          id: "dashboard-visual-stability",
          description: "Dashboard",
          target: "localPreview",
          severity: "high",
          runOn: { pullRequest: true },
          selectors: {
            mustExist: ["[data-testid='dashboard-page']"],
            mustNotExist: ["[data-testid='login-page']"],
            textMustExist: ["Demo metrics loaded"]
          },
          screenshots: [{ name: "dashboard", route: "/", viewport: "desktop" }]
        }
      ],
      viewports: { desktop: { width: 1440, height: 900 } }
    });

    const content = buildSpecContent({
      rootDir: "/tmp/sample",
      contracts: config.contracts,
      targets: config.targets,
      viewports: config.viewports
    });

    expect(content).toContain("[data-testid='dashboard-page']");
    expect(content).toContain("\"route\": \"/\"");
    expect(content).toContain("\"width\": 1440");
    expect(content).toContain("VISUAL_HIVE_MUTATION_OPERATOR");
    expect(content).toContain("hide-critical-button");
    expect(content).toContain("Generated by Visual Hive");
    expect(content).toContain("Missing screenshot baseline in CI mode");
  });

  it("includes generated spec path in collected artifacts", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-artifacts-"));
    tempDirs.push(tempRoot);
    const generatedDir = path.join(tempRoot, ".visual-hive", "generated");
    await mkdir(generatedDir, { recursive: true });
    await writeFile(path.join(generatedDir, "visual-hive.generated.spec.ts"), "// generated", "utf8");

    const artifacts = await collectArtifacts(tempRoot);

    expect(artifacts.some((artifact) => artifact.endsWith("visual-hive.generated.spec.ts"))).toBe(true);
  });

  it("returns an excellent target startup timeout error", async () => {
    await expect(
      waitForServerUrl({
        url: "http://127.0.0.1:9",
        timeoutMs: 1,
        command: "npm run preview -- --port 9",
        logTail: () => "secret=abc\nserver failed"
      })
    ).rejects.toThrow(/Target server failed to start/);
    await expect(
      waitForServerUrl({
        url: "http://127.0.0.1:9?token=abc",
        timeoutMs: 1,
        command: "npm run preview -- --port 9",
        logTail: () => "secret=abc"
      })
    ).rejects.toThrow(/token=\[REDACTED\]/);
  });
});
