import { constants } from "node:fs";
import { access, mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { VisualHiveConfigSchema } from "@visual-hive/core";
import { buildSpecContent, generatePlaywrightSpec } from "../src/generator.js";
import { collectArtifacts } from "../src/artifactCollector.js";
import { waitForServerUrl } from "../src/serverManager.js";
import { comparePngSnapshot } from "../src/visualDiff.js";
import { runPlaywrightContracts } from "../src/runner.js";
import { PNG } from "pngjs";

const tempDirs: string[] = [];

afterEach(async () => {
  for (const dir of tempDirs.splice(0)) {
    await rm(dir, { recursive: true, force: true });
  }
});

describe("buildSpecContent", () => {
  it("includes expected selectors, routes, viewport usage, and mutation hook", () => {
    const config = VisualHiveConfigSchema.parse({
      project: { name: "sample", type: "react-vite", defaultBranch: "main" },
      targets: {
        localPreview: {
          kind: "url",
          url: "http://127.0.0.1:4173",
          prSafe: true,
          cost: "cheap"
        }
      },
      contracts: [
        {
          id: "dashboard-visual-stability",
          description: "Dashboard",
          target: "localPreview",
          severity: "high",
          runOn: { pullRequest: true },
          waitFor: [{ selector: "[data-testid='dashboard-page']", state: "visible", timeoutMs: 5000 }],
          steps: [
            { action: "click", selector: "[data-testid='critical-action-button']", description: "Critical action is clickable." },
            { action: "assertText", selector: ".data-status", text: "Demo metrics loaded" }
          ],
          failOnConsoleError: true,
          expectedConsoleErrors: ["Known harmless"],
          selectors: {
            mustExist: ["[data-testid='dashboard-page']"],
            mustNotExist: ["[data-testid='login-page']"],
            textMustExist: ["Demo metrics loaded"]
          },
          screenshots: [{ name: "dashboard", route: "/", viewport: "desktop" }]
        }
      ],
      viewports: { desktop: { width: 1440, height: 900 } }
    });

    const content = buildSpecContent({
      rootDir: "/tmp/sample",
      contracts: config.contracts,
      targets: config.targets,
      viewports: config.viewports,
      visual: config.visual
    });

    expect(content).toContain("[data-testid='dashboard-page']");
    expect(content).toContain("\"route\": \"/\"");
    expect(content).toContain("\"width\": 1440");
    expect(content).toContain("VISUAL_HIVE_MUTATION_OPERATOR");
    expect(content).toContain("hide-critical-button");
    expect(content).toContain("route-guard-bypass");
    expect(content).toContain("hidden-error-banner");
    expect(content).toContain("broken-image");
    expect(content).toContain("removed-accessible-name");
    expect(content).toContain("theme-token-drift");
    expect(content).toContain("stale-loading-state");
    expect(content).toContain("Generated by Visual Hive");
    expect(content).toContain("Missing screenshot baseline in CI mode");
    expect(content).toContain("domcontentloaded");
    expect(content).not.toContain("networkidle");
    expect(content).toContain("visualHiveCi === \"false\" ? false");
    expect(content).toContain("applyWaits");
    expect(content).toContain("runFlowSteps");
    expect(content).toContain("executeFlowStep");
    expect(content).toContain("flowSteps");
    expect(content).toContain("Critical action is clickable.");
    expect(content).toContain("visibleStepValue");
    expect(content).toContain("page.on(\"pageerror\"");
    expect(content).toContain("page.on(\"response\"");
    expect(content).toContain("consoleErrors.push({ type: \"console\", message: sanitizeText");
    expect(content).toContain("pageErrors.push({ type: \"page\", message: sanitizeText");
    expect(content).toContain("url: sanitizeText(response.url())");
    expect(content).toContain("actualDiffPixelRatio");
    expect(content).toContain("pixelmatch");
    expect(content).toContain("message.includes(pattern)");
  });

  it("includes generated spec path in collected artifacts", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-artifacts-"));
    tempDirs.push(tempRoot);
    const generatedDir = path.join(tempRoot, ".visual-hive", "generated");
    await mkdir(generatedDir, { recursive: true });
    await writeFile(path.join(generatedDir, "visual-hive.generated.spec.ts"), "// generated", "utf8");

    const artifacts = await collectArtifacts(tempRoot);

    expect(artifacts.some((artifact) => artifact.endsWith("visual-hive.generated.spec.ts"))).toBe(true);
  });

  it("serializes resolved deploy preview URLs into generated specs", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-deploy-preview-spec-"));
    tempDirs.push(tempRoot);
    const config = VisualHiveConfigSchema.parse({
      project: { name: "preview-spec" },
      targets: {
        preview: {
          kind: "deployPreview",
          provider: "vercel",
          urlEnv: "VERCEL_URL"
        }
      },
      contracts: [
        {
          id: "preview-dashboard",
          description: "Preview dashboard",
          target: "preview",
          runOn: { pullRequest: true },
          screenshots: [{ name: "home", route: "/", viewport: "desktop" }]
        }
      ]
    });

    const generated = await generatePlaywrightSpec({
      rootDir: tempRoot,
      config,
      plan: {
        schemaVersion: 1,
        project: "preview-spec",
        mode: "pr",
        generatedAt: "2026-06-16T00:00:00.000Z",
        changedFiles: [],
        effectiveChangedFiles: [],
        ignoredChangedFiles: [],
        targets: [{ id: "preview", kind: "deployPreview", url: "https://preview.example.com", prSafe: true, cost: "cheap" }],
        items: [
          {
            contractId: "preview-dashboard",
            targetId: "preview",
            targetUrl: "https://preview.example.com",
            severity: "medium",
            cost: "cheap",
            reasons: ["runOn.pullRequest=true"],
            screenshots: ["home:/:desktop"]
          }
        ],
        excluded: [],
        mutation: { enabled: false, operators: [], minScore: 0.7, reasons: [] },
        providerPolicy: []
      }
    });

    expect(generated.content).toContain("\"kind\": \"deployPreview\"");
    expect(generated.content).toContain("\"url\": \"https://preview.example.com\"");
    await expect(access(generated.path, constants.F_OK)).resolves.toBeUndefined();
  });

  it("serializes storybook targets and component story routes into generated specs", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-storybook-spec-"));
    tempDirs.push(tempRoot);
    const config = VisualHiveConfigSchema.parse({
      project: { name: "storybook-spec", setupProfile: "component-storybook" },
      targets: {
        componentLibrary: {
          kind: "storybook",
          serve: "npm run storybook -- --host 127.0.0.1 --port 6006",
          url: "http://127.0.0.1:6006",
          stories: ["src/**/*.stories.tsx"],
          components: ["src/components/**"]
        }
      },
      contracts: [
        {
          id: "storybook-button",
          description: "Button story",
          target: "componentLibrary",
          runOn: { pullRequest: true },
          screenshots: [{ name: "button-primary", route: "/?path=/story/button--primary", viewport: "desktop" }]
        }
      ]
    });

    const generated = await generatePlaywrightSpec({
      rootDir: tempRoot,
      config,
      plan: {
        schemaVersion: 1,
        project: "storybook-spec",
        mode: "pr",
        generatedAt: "2026-06-16T00:00:00.000Z",
        changedFiles: [],
        effectiveChangedFiles: [],
        ignoredChangedFiles: [],
        targets: [{ id: "componentLibrary", kind: "storybook", url: "http://127.0.0.1:6006", prSafe: true, cost: "cheap" }],
        items: [
          {
            contractId: "storybook-button",
            targetId: "componentLibrary",
            targetUrl: "http://127.0.0.1:6006",
            severity: "medium",
            cost: "cheap",
            reasons: ["runOn.pullRequest=true"],
            screenshots: ["button-primary:/?path=/story/button--primary:desktop"]
          }
        ],
        excluded: [],
        mutation: { enabled: false, operators: [], minScore: 0.7, reasons: [] },
        providerPolicy: []
      }
    });

    expect(generated.content).toContain("\"kind\": \"storybook\"");
    expect(generated.content).toContain("\"url\": \"http://127.0.0.1:6006\"");
    expect(generated.content).toContain("\"/?path=/story/button--primary\"");
    await expect(access(generated.path, constants.F_OK)).resolves.toBeUndefined();
  });

  it("creates a missing baseline locally and serializes diff metadata", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-visual-diff-"));
    tempDirs.push(tempRoot);
    const baselinePath = path.join(tempRoot, ".visual-hive", "snapshots", "baseline.png");
    const actualPath = path.join(tempRoot, ".visual-hive", "artifacts", "screenshots", "actual.png");
    const diffPath = path.join(tempRoot, ".visual-hive", "artifacts", "screenshots", "diff.png");
    const visual = VisualHiveConfigSchema.parse({
      project: { name: "sample" },
      targets: { local: { kind: "url", url: "http://127.0.0.1:4173" } },
      contracts: [{ id: "c", description: "c", target: "local" }]
    }).visual;

    const result = await comparePngSnapshot({
      baselinePath,
      actualPath,
      diffPath,
      actualBuffer: pngBuffer([255, 0, 0, 255]),
      ci: false,
      visual,
      contractId: "c",
      name: "home",
      route: "/",
      viewport: "desktop"
    });

    expect(result.status).toBe("created");
    expect(result.contractId).toBe("c");
    expect(result.screenshotName).toBe("home");
    expect(result.actualDiffPixelRatio).toBe(0);
    expect(result.actualDiffPixels).toBe(0);
    await expect(access(baselinePath, constants.F_OK)).resolves.toBeUndefined();
    await expect(access(actualPath, constants.F_OK)).resolves.toBeUndefined();
  });

  it("fails missing baselines in CI mode", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-missing-baseline-"));
    tempDirs.push(tempRoot);
    const visual = VisualHiveConfigSchema.parse({
      project: { name: "sample" },
      targets: { local: { kind: "url", url: "http://127.0.0.1:4173" } },
      contracts: [{ id: "c", description: "c", target: "local" }]
    }).visual;

    const result = await comparePngSnapshot({
      baselinePath: path.join(tempRoot, "baseline.png"),
      actualPath: path.join(tempRoot, "actual.png"),
      diffPath: path.join(tempRoot, "diff.png"),
      actualBuffer: pngBuffer([255, 0, 0, 255]),
      ci: true,
      visual,
      name: "home",
      route: "/",
      viewport: "desktop"
    });

    expect(result.status).toBe("missing_baseline");
    expect(result.message).toContain("Missing screenshot baseline");
    expect(result.actualDiffPixelRatio).toBe(1);
    expect(result.actualDiffPixels).toBe(1);
  });

  it("passes when the actual screenshot matches the baseline", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-identical-baseline-"));
    tempDirs.push(tempRoot);
    const baselinePath = path.join(tempRoot, "baseline.png");
    const image = pngBuffer([255, 0, 0, 255]);
    await writeFile(baselinePath, image);
    const visual = VisualHiveConfigSchema.parse({
      project: { name: "sample" },
      targets: { local: { kind: "url", url: "http://127.0.0.1:4173" } },
      contracts: [{ id: "c", description: "c", target: "local" }]
    }).visual;

    const result = await comparePngSnapshot({
      baselinePath,
      actualPath: path.join(tempRoot, "actual.png"),
      diffPath: path.join(tempRoot, "diff.png"),
      actualBuffer: image,
      ci: true,
      visual,
      contractId: "c",
      name: "home",
      route: "/",
      viewport: "desktop"
    });

    expect(result.status).toBe("passed");
    expect(result.actualDiffPixels).toBe(0);
    expect(result.actualDiffPixelRatio).toBe(0);
  });

  it("fails when visual diff exceeds tolerance and writes diff metadata", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-diff-baseline-"));
    tempDirs.push(tempRoot);
    const baselinePath = path.join(tempRoot, "baseline.png");
    const diffPath = path.join(tempRoot, "diff.png");
    await writeFile(baselinePath, pngBuffer([0, 0, 255, 255]));
    const visual = {
      maxDiffPixelRatio: 0,
      updateSnapshots: false,
      failOnMissingBaselineInCI: true,
      snapshotDir: ".visual-hive/snapshots",
      artifactDir: ".visual-hive/artifacts"
    };

    const result = await comparePngSnapshot({
      baselinePath,
      actualPath: path.join(tempRoot, "actual.png"),
      diffPath,
      actualBuffer: pngBuffer([255, 0, 0, 255]),
      ci: true,
      visual,
      contractId: "c",
      name: "home",
      route: "/",
      viewport: "desktop"
    });

    expect(result.status).toBe("failed");
    expect(result.diffPath).toBe(diffPath);
    expect(result.actualDiffPixels).toBeGreaterThan(0);
    await expect(access(diffPath, constants.F_OK)).resolves.toBeUndefined();
  });

  it("updates snapshots when visual.updateSnapshots is enabled", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-update-baseline-"));
    tempDirs.push(tempRoot);
    const baselinePath = path.join(tempRoot, "baseline.png");
    await writeFile(baselinePath, pngBuffer([0, 0, 255, 255]));
    const visual = {
      maxDiffPixelRatio: 0.01,
      updateSnapshots: true,
      failOnMissingBaselineInCI: true,
      snapshotDir: ".visual-hive/snapshots",
      artifactDir: ".visual-hive/artifacts"
    };

    const result = await comparePngSnapshot({
      baselinePath,
      actualPath: path.join(tempRoot, "actual.png"),
      diffPath: path.join(tempRoot, "diff.png"),
      actualBuffer: pngBuffer([255, 0, 0, 255]),
      ci: true,
      visual,
      contractId: "c",
      name: "home",
      route: "/",
      viewport: "desktop"
    });

    expect(result.status).toBe("passed");
    expect(result.totalPixels).toBe(1);
  });

  it("returns an excellent target startup timeout error", async () => {
    await expect(
      waitForServerUrl({
        url: "http://127.0.0.1:9",
        timeoutMs: 1,
        command: "npm run preview -- --port 9",
        logTail: () => "secret=abc\nserver failed"
      })
    ).rejects.toThrow(/Target server failed to start/);
    await expect(
      waitForServerUrl({
        url: "http://127.0.0.1:9?token=abc",
        timeoutMs: 1,
        command: "npm run preview -- --port 9",
        logTail: () => "secret=abc"
      })
    ).rejects.toThrow(/token=\[REDACTED\]/);
  });

  it("returns a failed report with sanitized lifecycle evidence when a target cannot start", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-startup-report-"));
    tempDirs.push(tempRoot);
    const config = VisualHiveConfigSchema.parse({
      project: { name: "startup-report" },
      targets: {
        local: {
          kind: "command",
          serve: "node -e \"console.error('secret=abc'); process.exit(1)\"",
          url: "http://127.0.0.1:9?token=abc",
          prSafe: true
        }
      },
      contracts: [
        {
          id: "home",
          description: "Home",
          target: "local",
          runOn: { pullRequest: true },
          selectors: { mustExist: ["main"] }
        }
      ]
    });
    const plan = {
      schemaVersion: 1 as const,
      project: "startup-report",
      mode: "pr" as const,
      generatedAt: "2026-01-01T00:00:00.000Z",
      changedFiles: [],
      effectiveChangedFiles: [],
      ignoredChangedFiles: [],
      targets: [{ id: "local", kind: "command", url: "http://127.0.0.1:9?token=abc", prSafe: true, cost: "medium" }],
      items: [
        {
          contractId: "home",
          targetId: "local",
          targetUrl: "http://127.0.0.1:9?token=abc",
          severity: "medium" as const,
          cost: "medium" as const,
          reasons: ["test"],
          screenshots: []
        }
      ],
      excluded: [],
      mutation: { enabled: false, operators: [], minScore: 0.7, reasons: [] }
    };

    const { report, exitCode } = await runPlaywrightContracts({ config, plan, rootDir: tempRoot, skipInstall: true, skipBuild: true });

    expect(exitCode).toBe(1);
    expect(report.status).toBe("failed");
    expect(report.verdictSummary?.visualHiveVerdict).toBe("blocked");
    expect(report.verdictSummary?.blockedBecause).toContain("playwright.deterministic_run");
    expect(report.verdictSummary?.blockedBecause).toContain("visual_hive.target_lifecycle_failure");
    expect(report.verdictContributions?.some((contribution) => contribution.key === "playwright.contract_result.home" && contribution.status === "blocked" && contribution.gating)).toBe(true);
    expect(report.generatedSpecPath).toContain("visual-hive.generated.spec.ts");
    expect(report.targetLifecycle.some((event) => event.phase === "serve" && event.status === "failed")).toBe(true);
    expect(report.providerResults?.find((provider) => provider.providerId === "playwright")?.status).toBe("failed");
    expect(report.results[0]?.errors.join("\n")).toContain("Target server failed to start");
    expect(JSON.stringify(report)).toContain("token=[REDACTED]");
    expect(JSON.stringify(report)).not.toContain("secret=abc");
  });

  it("records lifecycle evidence when a storybook target cannot start", async () => {
    const tempRoot = await mkdtemp(path.join(os.tmpdir(), "visual-hive-storybook-startup-"));
    tempDirs.push(tempRoot);
    const config = VisualHiveConfigSchema.parse({
      project: { name: "storybook-startup", setupProfile: "component-storybook" },
      targets: {
        componentLibrary: {
          kind: "storybook",
          serve: "node -e \"process.exit(1)\"",
          url: "http://127.0.0.1:9",
          stories: ["src/**/*.stories.tsx"],
          components: ["src/components/**"],
          prSafe: true
        }
      },
      contracts: [
        {
          id: "storybook-home",
          description: "Storybook home",
          target: "componentLibrary",
          runOn: { pullRequest: true }
        }
      ]
    });
    const plan = {
      schemaVersion: 1 as const,
      project: "storybook-startup",
      mode: "pr" as const,
      generatedAt: "2026-01-01T00:00:00.000Z",
      changedFiles: [],
      effectiveChangedFiles: [],
      ignoredChangedFiles: [],
      targets: [{ id: "componentLibrary", kind: "storybook", url: "http://127.0.0.1:9", prSafe: true, cost: "cheap" as const }],
      items: [
        {
          contractId: "storybook-home",
          targetId: "componentLibrary",
          targetUrl: "http://127.0.0.1:9",
          severity: "medium" as const,
          cost: "cheap" as const,
          reasons: ["test"],
          screenshots: []
        }
      ],
      excluded: [],
      mutation: { enabled: false, operators: [], minScore: 0.7, reasons: [] },
      providerPolicy: []
    };

    const { report, exitCode } = await runPlaywrightContracts({ config, plan, rootDir: tempRoot, skipInstall: true, skipBuild: true });

    expect(exitCode).toBe(1);
    expect(report.status).toBe("failed");
    expect(report.verdictSummary?.visualHiveVerdict).toBe("blocked");
    expect(report.verdictContributions?.map((contribution) => contribution.key)).toContain("playwright.contract_result.storybook-home");
    expect(report.selectedTargets[0]?.kind).toBe("storybook");
    expect(report.targetLifecycle.some((event) => event.targetId === "componentLibrary" && event.serviceName === "storybook" && event.status === "failed")).toBe(true);
  });
});

function pngBuffer(rgba: [number, number, number, number]): Buffer {
  const image = new PNG({ width: 1, height: 1 });
  image.data[0] = rgba[0];
  image.data[1] = rgba[1];
  image.data[2] = rgba[2];
  image.data[3] = rgba[3];
  return PNG.sync.write(image);
}
