import path from "node:path";
import { createRequire } from "node:module";
import {
  API_500_MUTATION_MARKER,
  VISUAL_REPAIR_IMAGE_COMPARISON_ALGORITHM,
  VISUAL_REPAIR_IMAGE_COMPARISON_DIAGNOSTIC_COLORS,
  writeText,
  type Plan,
  type VisualHiveConfig
} from "@visual-hive/core";

const trustedRequire = createRequire(import.meta.url);

export interface TrustedPlaywrightDependencies {
  playwrightTest: string;
  pixelmatch: string;
  pngjs: string;
  playwrightVersion: string;
}

export interface GenerateSpecOptions {
  config: VisualHiveConfig;
  plan: Plan;
  rootDir: string;
  outputDir?: string;
}

export interface GeneratedSpec {
  path: string;
  content: string;
  configPath: string;
  configContent: string;
}

export async function generatePlaywrightSpec(options: GenerateSpecOptions): Promise<GeneratedSpec> {
  const outputDir = options.outputDir ?? path.join(options.rootDir, ".visual-hive", "generated");
  const specPath = path.join(outputDir, "visual-hive.generated.spec.ts");
  const configPath = path.join(outputDir, "visual-hive.generated.config.cjs");
  const selectedIds = new Set(options.plan.items.map((item) => item.contractId));
  const contracts = options.config.contracts.filter((contract) => selectedIds.has(contract.id));
  const selectedTargetIds = new Set(options.plan.targets.map((target) => target.id));
  const targets = Object.fromEntries(Object.entries(normalizeTargets(options.config.targets, options.plan.targets)).filter(([targetId]) => selectedTargetIds.has(targetId)));
  const content = buildSpecContent({
    rootDir: options.rootDir,
    contracts,
    targets,
    viewports: options.config.viewports,
    visual: options.config.visual,
    dependencies: resolveTrustedPlaywrightDependencies()
  });
  await writeText(specPath, content);
  const configContent = buildPlaywrightConfigContent();
  await writeText(configPath, configContent);
  return { path: specPath, content, configPath, configContent };
}

export function buildPlaywrightConfigContent(): string {
  return `// Generated by Visual Hive.
// Keep generated deterministic specs discoverable even though .visual-hive is hidden.
module.exports = {
  testDir: __dirname,
  testMatch: "visual-hive.generated.spec.ts",
  fullyParallel: false,
  workers: 1
};
`;
}

function resolveTrustedPlaywrightDependencies(): TrustedPlaywrightDependencies {
  const playwrightPackage = trustedRequire("@playwright/test/package.json") as { version?: unknown };
  if (typeof playwrightPackage.version !== "string" || !playwrightPackage.version) throw new Error("Visual Hive packaged Playwright version is unavailable.");
  return {
    playwrightTest: trustedRequire.resolve("@playwright/test"),
    pixelmatch: trustedRequire.resolve("pixelmatch"),
    pngjs: trustedRequire.resolve("pngjs"),
    playwrightVersion: playwrightPackage.version
  };
}

function normalizeTargets(targets: VisualHiveConfig["targets"], planTargets: Plan["targets"] = []): VisualHiveConfig["targets"] {
  const normalized: VisualHiveConfig["targets"] = {};
  const plannedUrls = new Map(planTargets.map((target) => [target.id, target.url]));
  for (const [id, target] of Object.entries(targets)) {
    const plannedUrl = plannedUrls.get(id);
    if (plannedUrl) {
      normalized[id] = { ...target, url: plannedUrl };
      continue;
    }
    if (target.url || (target.kind !== "commandGroup" && target.kind !== "protected")) {
      normalized[id] = target;
      continue;
    }
    normalized[id] = {
      ...target,
      url: target.services[0]?.url
    };
  }
  return normalized;
}

export function buildSpecContent(input: {
  rootDir: string;
  contracts: VisualHiveConfig["contracts"];
  targets: VisualHiveConfig["targets"];
  viewports: VisualHiveConfig["viewports"];
  visual: VisualHiveConfig["visual"];
  dependencies?: TrustedPlaywrightDependencies;
}): string {
  const dependencies = input.dependencies ?? resolveTrustedPlaywrightDependencies();
  return `// Generated by Visual Hive.
// Artifact: .visual-hive/generated/visual-hive.generated.spec.ts
// This file is intentionally readable so CI artifacts can be used for debugging.

  import { createHash, createHmac, timingSafeEqual } from "node:crypto";
  import { constants, existsSync } from "node:fs";
  import { lstat, mkdir, open, readFile, realpath, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import os from "node:os";
import path from "node:path";

const visualHiveRequire = createRequire(${JSON.stringify(dependencies.playwrightTest)});
const { test, expect } = visualHiveRequire(${JSON.stringify(dependencies.playwrightTest)});
const pixelmatchModule = visualHiveRequire(${JSON.stringify(dependencies.pixelmatch)});
const pixelmatch = pixelmatchModule.default ?? pixelmatchModule;
const { PNG } = visualHiveRequire(${JSON.stringify(dependencies.pngjs)});

// ---- Serialized Visual Hive plan inputs ----
const rootDir = ${JSON.stringify(input.rootDir)};
const contracts = ${JSON.stringify(input.contracts, null, 2)};
const targets = ${JSON.stringify(input.targets, null, 2)};
const viewports = ${JSON.stringify(input.viewports, null, 2)};
const visual = ${JSON.stringify(input.visual, null, 2)};
const snapshotDir = path.resolve(rootDir, visual.snapshotDir ?? ".visual-hive/snapshots", ...(visual.baselinePlatform === "platform" ? [process.platform] : []));
const artifactDir = path.resolve(rootDir, visual.artifactDir ?? ".visual-hive/artifacts");
const visualHiveCi = process.env.VISUAL_HIVE_CI;
const ciMode = visualHiveCi === "true" ? true : visualHiveCi === "false" ? false : process.env.CI === "true";
const mutationOperator = process.env.VISUAL_HIVE_MUTATION_OPERATOR || "";
const mutationOperators = parseMutationOperators();
const mutationContractMatrix = parseMutationContractMatrix();
const api500MutationMarker = ${JSON.stringify(API_500_MUTATION_MARKER)};
const visualRepairImageComparisonAlgorithm = ${JSON.stringify(VISUAL_REPAIR_IMAGE_COMPARISON_ALGORITHM)};
const visualRepairImageComparisonDiagnosticColors = ${JSON.stringify(VISUAL_REPAIR_IMAGE_COMPARISON_DIAGNOSTIC_COLORS)};
const runtimeSidecarPath = process.env.VISUAL_HIVE_RUNTIME_SIDECAR || "";
const executionNonce = process.env.VISUAL_HIVE_EXECUTION_NONCE || "";
const executionPayload = process.env.VISUAL_HIVE_EXECUTION_PAYLOAD || "";
const executionMac = process.env.VISUAL_HIVE_EXECUTION_MAC || "";
const executionBindingJson = process.env.VISUAL_HIVE_EXECUTION_BINDING || "";
const generatedSpecPath = process.env.VISUAL_HIVE_SPEC_PATH || "";
const generatedConfigPath = process.env.VISUAL_HIVE_CONFIG_PATH || "";
const evidenceRoot = process.env.VISUAL_HIVE_EVIDENCE_ROOT || "";
const trustedPlaywrightVersion = ${JSON.stringify(dependencies.playwrightVersion)};
let verifiedExecutionBinding;
let verifiedEvidenceRoot;
let exclusiveEvidenceWrites = false;

// ---- Contract execution ----
test.describe("visual-hive generated deterministic contracts", () => {
  test.beforeAll(async ({ browser, browserName }) => {
    const executionBinding = await verifyExecutionBinding();
    if (!runtimeSidecarPath) return;
    const page = await browser.newPage();
    try {
      const browserRuntime = await page.evaluate(() => {
        const fontNames = ["Arial", "Calibri", "Courier New", "Georgia", "Segoe UI", "Times New Roman", "Verdana"];
        return {
          locale: navigator.language || "und",
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "unknown",
          userAgent: navigator.userAgent,
          deviceScaleFactor: window.devicePixelRatio,
          fonts: fontNames.map((name) => ({ name, available: document.fonts.check(\`12px "\${name}"\`) }))
        };
      });
      const playwrightVersion = trustedPlaywrightVersion;
      await writeEvidenceFileExclusive(
        runtimeSidecarPath,
        JSON.stringify(
          {
            schemaVersion: "visual-hive.playwright-runtime.v1",
            executionBinding,
            capturedAt: new Date().toISOString(),
            browser: { name: browserName, version: browser.version() },
            environment: {
              os: \`\${process.platform} \${os.release()}\`,
              architecture: process.arch,
              nodeVersion: process.version,
              playwrightVersion,
              locale: browserRuntime.locale,
              timezone: browserRuntime.timezone,
              userAgent: browserRuntime.userAgent,
              deviceScaleFactor: browserRuntime.deviceScaleFactor,
              fonts: browserRuntime.fonts
            }
          },
          null,
          2
        ) + "\\n",
        "utf8"
      );
    } finally {
      await page.close();
    }
  });
  for (const contract of contracts) {
    for (const activeMutationOperator of mutationOperators.length ? mutationOperators : [mutationOperator]) {
    if (activeMutationOperator && !mutationAppliesToContract(activeMutationOperator, contract.id)) continue;
    test(activeMutationOperator ? \`mutation:\${activeMutationOperator}:contract:\${contract.id}\` : \`contract:\${contract.id}\`, async ({ page }) => {
      test.setTimeout(contract.timeoutMs ?? 30000);
      const target = targets[contract.target];
      const startedAt = Date.now();
      const selectorAssertions = [];
      const flowSteps = [];
      const screenshotAssertions = [];
      const consoleErrors = [];
      const pageErrors = [];
      const networkErrors = [];
      const artifacts = [];
      const errors = [];
      const screenshotFailures = [];
      let contractStatus = "passed";

      page.on("console", (message) => {
        if (message.type() === "error" && !isExpectedConsoleError(contract, message.text())) {
          consoleErrors.push({ type: "console", message: sanitizeText(message.text()) });
        }
      });
      page.on("pageerror", (error) => {
        pageErrors.push({ type: "page", message: sanitizeText(error.message) });
      });
      page.on("response", (response) => {
        if (response.status() >= 400) {
          networkErrors.push({
            type: "network",
            url: sanitizeText(response.url()),
            status: response.status(),
            statusText: sanitizeText(response.statusText())
          });
        }
      });

      try {
        const routeMutationTracker = await applyRouteMutation(page, activeMutationOperator, contract.timeoutMs);
        await page.addInitScript((operator) => {
          window.localStorage.setItem("visual-hive-mutation", operator);
        }, activeMutationOperator);

        const assertionRoute = contract.screenshots[0]?.route ?? "/";
        await page.setViewportSize(viewports.desktop ?? { width: 1440, height: 900 });
        await page.goto(joinUrl(target.url, assertionRoute), { waitUntil: "domcontentloaded" });
        await disableAnimations(page);
        await applyDomMutation(page, activeMutationOperator);
        await applyWaits(page, contract, selectorAssertions);
        await assertSelectors(page, contract.selectors, selectorAssertions);
        await runFlowSteps(page, target, contract, flowSteps, activeMutationOperator);

        for (const shot of contract.screenshots) {
          const viewport = viewports[shot.viewport];
          if (!viewport) {
            throw new Error(\`Unknown viewport "\${shot.viewport}" in screenshot "\${shot.name}"\`);
          }
          await page.setViewportSize(viewport);
          await page.goto(joinUrl(target.url, shot.route), { waitUntil: "domcontentloaded" });
          await disableAnimations(page);
          await applyDomMutation(page, activeMutationOperator);
          await applyWaits(page, contract, selectorAssertions);
          await assertSelectors(page, contract.selectors, selectorAssertions);
          const assertion = await compareScreenshot(page, contract.id, shot, artifacts, activeMutationOperator);
          screenshotAssertions.push(assertion);
          if (assertion.status === "created" && contractStatus !== "failed") {
            contractStatus = "created";
          }
          if (assertion.status === "failed" || assertion.status === "missing_baseline") {
            contractStatus = "failed";
            screenshotFailures.push(assertion.message ?? \`Screenshot assertion failed for \${contract.id}/\${shot.name}: diffRatio=\${assertion.actualDiffPixelRatio}\`);
          }
        }

        await finalizeApi500MutationObservation(page, contract, activeMutationOperator, routeMutationTracker, selectorAssertions);

        if (contract.failOnConsoleError && (consoleErrors.length > 0 || pageErrors.length > 0)) {
          throw new Error(\`Unexpected console/page errors in \${contract.id}\`);
        }
        if (screenshotFailures.length > 0) {
          throw new Error(\`Screenshot assertions failed for \${contract.id}: \${screenshotFailures.join("; ")}\`);
        }
      } catch (error) {
        contractStatus = "failed";
        errors.push(sanitizeText(error instanceof Error ? error.message : String(error)));
        throw error;
      } finally {
        const resultPath = path.join(artifactDir, "results", activeMutationOperator ? \`\${safeName(activeMutationOperator)}__\${safeName(contract.id)}.json\` : \`\${safeName(contract.id)}.json\`);
        artifacts.push(artifactReference(resultPath));
        await mkdir(path.dirname(resultPath), { recursive: true });
        const executionBinding = await verifyExecutionBinding();
        await writeEvidenceFileExclusive(
          resultPath,
          JSON.stringify(
            {
              schemaVersion: "visual-hive.playwright-contract-result.v1",
              executionBinding,
              result: {
                contractId: contract.id,
                mutationOperator: activeMutationOperator || undefined,
                targetId: contract.target,
                status: contractStatus,
                durationMs: Date.now() - startedAt,
                errors,
                artifacts,
                selectorAssertions,
                flowSteps,
                screenshotAssertions,
                consoleErrors,
                pageErrors,
                networkErrors,
                reproductionCommand: "visual-hive run --ci"
              }
            },
            null,
            2
          ),
          "utf8"
        );
      }
    });
    }
  }
});

async function runFlowSteps(page, target, contract, flowSteps, activeMutationOperator = "") {
  for (const step of contract.steps ?? []) {
    const startedAt = Date.now();
    const result = {
      action: step.action,
      description: step.description,
      selector: step.selector,
      route: step.route,
      value: visibleStepValue(step),
      status: "passed",
      durationMs: 0
    };
    try {
      await executeFlowStep(page, target, step, activeMutationOperator);
      result.durationMs = Date.now() - startedAt;
      flowSteps.push(result);
    } catch (error) {
      result.status = "failed";
      result.durationMs = Date.now() - startedAt;
      result.message = sanitizeText(error instanceof Error ? error.message : String(error));
      flowSteps.push(result);
      throw error;
    }
  }
}

async function executeFlowStep(page, target, step, activeMutationOperator = "") {
  const timeout = step.timeoutMs ?? 5000;
  if (step.action === "goto") {
    await page.goto(joinUrl(target.url, step.route), { waitUntil: "domcontentloaded" });
    await disableAnimations(page);
    await applyDomMutation(page, activeMutationOperator);
    return;
  }
  if (step.action === "click") {
    const locator = page.locator(step.selector).first();
    await locator.waitFor({ state: "visible", timeout });
    await locator.scrollIntoViewIfNeeded({ timeout });
    await locator.click({ timeout });
    return;
  }
  if (step.action === "fill") {
    await page.locator(step.selector).first().fill(step.value ?? "", { timeout });
    return;
  }
  if (step.action === "press") {
    await page.locator(step.selector).first().press(step.key, { timeout });
    return;
  }
  if (step.action === "waitFor") {
    await page.locator(step.selector).first().waitFor({ state: step.state ?? "visible", timeout });
    return;
  }
  if (step.action === "assertVisible") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector to be visible: \${step.selector}\`).toBeVisible({ timeout });
    return;
  }
  if (step.action === "assertHidden") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector to be hidden: \${step.selector}\`).toBeHidden({ timeout });
    return;
  }
  if (step.action === "assertText") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector text: \${step.selector}\`).toContainText(step.text ?? "", { timeout });
    return;
  }
  if (step.action === "assertUrl") {
    await expect(page, \`Expected URL to contain: \${step.value}\`).toHaveURL(new RegExp(escapeRegExp(step.value ?? "")), { timeout });
    return;
  }
  throw new Error(\`Unsupported Visual Hive flow step action: \${step.action}\`);
}

function visibleStepValue(step) {
  if (step.action === "fill") return step.value ? "[configured]" : undefined;
  return step.value ?? step.key ?? step.text;
}

async function applyWaits(page, contract, assertions) {
  for (const wait of contract.waitFor ?? []) {
    const assertion = { kind: "waitFor", value: wait.selector, status: "passed" };
    try {
      await page.locator(wait.selector).first().waitFor({ state: wait.state ?? "visible", timeout: wait.timeoutMs ?? 5000 });
      assertions.push(assertion);
    } catch (error) {
      assertion.status = "failed";
      assertion.message = error instanceof Error ? error.message : String(error);
      assertions.push(assertion);
      throw error;
    }
  }
}

async function assertSelectors(page, selectors = {}, assertions = []) {
  for (const selector of selectors.mustExist ?? []) {
    await recordAssertion(assertions, "mustExist", selector, async () => {
      await expect(page.locator(selector).first(), \`Expected selector to exist: \${selector}\`).toBeVisible();
    });
  }
  for (const selector of selectors.mustNotExist ?? []) {
    await recordAssertion(assertions, "mustNotExist", selector, async () => {
      await expect(page.locator(selector), \`Expected selector to be absent: \${selector}\`).toHaveCount(0);
    });
  }
  for (const text of selectors.textMustExist ?? []) {
    await recordAssertion(assertions, "textMustExist", text, async () => {
      await expect(page.getByText(text, { exact: false }).first(), \`Expected text to exist: \${text}\`).toBeVisible();
    });
  }
  for (const text of selectors.textMustNotExist ?? []) {
    await recordAssertion(assertions, "textMustNotExist", text, async () => {
      await expect(page.getByText(text, { exact: false }), \`Expected text to be absent: \${text}\`).toHaveCount(0);
    });
  }
}

async function recordAssertion(assertions, kind, value, fn) {
  const assertion = { kind, value, status: "passed" };
  try {
    await fn();
    assertions.push(assertion);
  } catch (error) {
    assertion.status = "failed";
    assertion.message = error instanceof Error ? error.message : String(error);
    assertions.push(assertion);
    throw error;
  }
}

// ---- Screenshot baseline handling ----
async function compareScreenshot(page, contractId, shot, artifacts, activeMutationOperator = "") {
  const baselinePath = path.join(snapshotDir, \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  const artifactPrefix = activeMutationOperator ? \`\${safeName(activeMutationOperator)}__\${safeName(contractId)}\` : safeName(contractId);
  const actualPath = path.join(artifactDir, "screenshots", \`\${artifactPrefix}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  const diffPath = path.join(artifactDir, "screenshots", \`\${artifactPrefix}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.diff.png\`);
  await mkdir(path.dirname(baselinePath), { recursive: true });
  await mkdir(path.dirname(actualPath), { recursive: true });
  const mask = (shot.mask ?? []).map((selector) => page.locator(selector));
  const actual = await page.screenshot({
    fullPage: shot.fullPage ?? true,
    animations: "disabled",
    caret: "initial",
    mask
  });
  artifacts.push(artifactReference(actualPath));

  const baseAssertion = {
    contractId,
    screenshotName: shot.name,
    name: shot.name,
    route: shot.route,
    viewport: shot.viewport,
    status: "passed",
    baselinePath: artifactReference(baselinePath),
    actualPath: artifactReference(actualPath),
    maxDiffPixelRatio: visual.maxDiffPixelRatio,
    maxDiffPixels: visual.maxDiffPixels,
    actualDiffPixelRatio: 0,
    actualDiffPixels: 0,
    diffPixels: 0,
    totalPixels: 0
  };

  if (!existsSync(baselinePath) || visual.updateSnapshots) {
    if (!existsSync(baselinePath) && ciMode && visual.failOnMissingBaselineInCI && !visual.updateSnapshots) {
      await writeEvidenceFileExclusive(actualPath, actual);
      return {
        ...baseAssertion,
        status: "missing_baseline",
        totalPixels: imagePixelCount(actual),
        diffPixels: imagePixelCount(actual),
        actualDiffPixels: imagePixelCount(actual),
        actualDiffPixelRatio: 1,
        message: \`Missing screenshot baseline in CI mode: \${artifactReference(baselinePath)}. Run visual-hive locally without --ci to create the baseline, review it, and commit the approved snapshot if your project tracks baselines.\`
      };
    }
    await writeFile(baselinePath, actual);
    await writeEvidenceFileExclusive(actualPath, actual);
    test.info().annotations.push({ type: "visual-hive", description: \`created baseline \${baselinePath}\` });
    return {
      ...baseAssertion,
      status: "created",
      totalPixels: imagePixelCount(actual)
    };
  }

  const baseline = await readFile(baselinePath);
  await writeEvidenceFileExclusive(actualPath, actual);
  const diff = diffImages(baseline, actual);
  if (diff.diffPixels > 0) {
    await writeEvidenceFileExclusive(diffPath, PNG.sync.write(diff.diffImage));
    artifacts.push(artifactReference(diffPath));
  }
  const failed =
    diff.actualDiffPixelRatio > visual.maxDiffPixelRatio ||
    (typeof visual.maxDiffPixels === "number" && diff.diffPixels > visual.maxDiffPixels);
  const dimensionsChanged =
    diff.beforeDimensions.width !== diff.afterDimensions.width ||
    diff.beforeDimensions.height !== diff.afterDimensions.height;
  return {
    ...baseAssertion,
    status: failed ? "failed" : "passed",
    diffPath: diff.diffPixels > 0 ? artifactReference(diffPath) : undefined,
    actualDiffPixelRatio: diff.actualDiffPixelRatio,
    actualDiffPixels: diff.diffPixels,
    diffPixels: diff.diffPixels,
    totalPixels: diff.totalPixels,
    message: dimensionsChanged
      ? "Screenshot dimensions changed from " + diff.beforeDimensions.width + "x" + diff.beforeDimensions.height +
        " to " + diff.afterDimensions.width + "x" + diff.afterDimensions.height +
        "; changed bounds: " + formatChangedBoundingBox(diff.changedBoundingBox) +
        "; comparator: " + visualRepairImageComparisonAlgorithm + "."
      : undefined
  };
}

function diffImages(baselineBuffer, actualBuffer) {
  const baseline = PNG.sync.read(baselineBuffer);
  const actual = PNG.sync.read(actualBuffer);
  if (baseline.width !== actual.width || baseline.height !== actual.height) {
    const width = Math.max(baseline.width, actual.width);
    const height = Math.max(baseline.height, actual.height);
    const diffImage = new PNG({ width, height });
    for (let y = 0; y < height; y += 1) {
      for (let x = 0; x < width; x += 1) {
        const baselineExists = x < baseline.width && y < baseline.height;
        const actualExists = x < actual.width && y < actual.height;
        if (baselineExists && !actualExists) {
          writeDiagnosticPixel(diffImage, x, y, visualRepairImageComparisonDiagnosticColors.removed);
        } else if (!baselineExists && actualExists) {
          writeDiagnosticPixel(diffImage, x, y, visualRepairImageComparisonDiagnosticColors.added);
        } else if (baselineExists && actualExists && !imagePixelsEqual(baseline, actual, x, y)) {
          writeDiagnosticPixel(diffImage, x, y, visualRepairImageComparisonDiagnosticColors.changed);
        }
      }
    }
    return {
      diffImage,
      diffPixels: width * height,
      totalPixels: width * height,
      actualDiffPixelRatio: 1,
      beforeDimensions: { width: baseline.width, height: baseline.height },
      afterDimensions: { width: actual.width, height: actual.height },
      changedBoundingBox: changedBoundingBox(diffImage)
    };
  }
  const diffImage = new PNG({ width: baseline.width, height: baseline.height });
  const diffPixels = pixelmatch(baseline.data, actual.data, diffImage.data, baseline.width, baseline.height, {
    threshold: 0.1,
    includeAA: false,
    diffMask: true,
    diffColor: visualRepairImageComparisonDiagnosticColors.changed.slice(0, 3)
  });
  const totalPixels = baseline.width * baseline.height;
  return {
    diffImage,
    diffPixels,
    totalPixels,
    actualDiffPixelRatio: totalPixels === 0 ? 0 : diffPixels / totalPixels,
    beforeDimensions: { width: baseline.width, height: baseline.height },
    afterDimensions: { width: actual.width, height: actual.height },
    changedBoundingBox: changedBoundingBox(diffImage)
  };
}

function imagePixelsEqual(before, after, x, y) {
  const beforeOffset = (y * before.width + x) * 4;
  const afterOffset = (y * after.width + x) * 4;
  for (let channel = 0; channel < 4; channel += 1) {
    if (before.data[beforeOffset + channel] !== after.data[afterOffset + channel]) return false;
  }
  return true;
}

function writeDiagnosticPixel(image, x, y, rgba) {
  const offset = (y * image.width + x) * 4;
  image.data[offset] = rgba[0];
  image.data[offset + 1] = rgba[1];
  image.data[offset + 2] = rgba[2];
  image.data[offset + 3] = rgba[3];
}

function changedBoundingBox(diffImage) {
  let minX = diffImage.width;
  let minY = diffImage.height;
  let maxX = -1;
  let maxY = -1;
  for (let y = 0; y < diffImage.height; y += 1) {
    for (let x = 0; x < diffImage.width; x += 1) {
      if (diffImage.data[(y * diffImage.width + x) * 4 + 3] === 0) continue;
      minX = Math.min(minX, x);
      minY = Math.min(minY, y);
      maxX = Math.max(maxX, x);
      maxY = Math.max(maxY, y);
    }
  }
  return maxX < 0 ? null : { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 };
}

function formatChangedBoundingBox(bounds) {
  return bounds ? bounds.x + "," + bounds.y + " " + bounds.width + "x" + bounds.height : "none";
}

function imagePixelCount(buffer) {
  const image = PNG.sync.read(buffer);
  return image.width * image.height;
}

// ---- Determinism helpers ----
async function disableAnimations(page) {
  await page.addStyleTag({
    content: \`*, *::before, *::after {
      animation-duration: 0.001s !important;
      animation-delay: 0s !important;
      transition-duration: 0.001s !important;
      transition-delay: 0s !important;
      scroll-behavior: auto !important;
    }\`
  });
}

// ---- Mutation hooks ----
async function applyRouteMutation(page, activeMutationOperator = mutationOperator, contractTimeoutMs) {
  let signalApi500Interception;
  const api500Interception = new Promise((resolve) => {
    signalApi500Interception = resolve;
  });
  const effectiveContractTimeoutMs = contractTimeoutMs ?? 30000;
  const tracker = {
    api500Intercepted: false,
    api500Interception,
    signalApi500Interception,
    contractDeadline: Date.now() + effectiveContractTimeoutMs,
    observationBudgetMs: Math.min(Math.max(Math.floor(effectiveContractTimeoutMs / 3), 100), 5000)
  };
  if (activeMutationOperator === "api-500") {
    await page.route("**/api/**", async (route) => {
      tracker.api500Intercepted = true;
      tracker.signalApi500Interception();
      try {
        await appendApi500MutationSentinel(page);
      } catch {
        // If the page context is replaced while the request is intercepted, the
        // API mutation still runs and remains a survivor until real evidence can
        // observe the sentinel. Never turn runner infrastructure into a kill.
      }
      await route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: api500MutationMarker }) });
    });
  }
  if (activeMutationOperator === "empty-data") {
    await page.route("**/api/**", async (route) => {
      await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ items: [], message: "" }) });
    });
  }
  if (activeMutationOperator === "broken-image") {
    await page.route(/.*\\.(png|jpg|jpeg|gif|webp|svg)(\\?.*)?$/i, async (route) => {
      await route.fulfill({ status: 404, contentType: "text/plain", body: "visual-hive broken-image mutation" });
    });
  }
  return tracker;
}

async function appendApi500MutationSentinel(page) {
  await page.evaluate((marker) => {
    const attribute = "data-visual-hive-api-500-mutation";
    if (document.querySelector(\`[\${attribute}="true"]\`)) return;
    const sentinel = document.createElement("span");
    sentinel.setAttribute(attribute, "true");
    sentinel.setAttribute("aria-hidden", "true");
    sentinel.hidden = true;
    sentinel.style.setProperty("display", "none", "important");
    sentinel.textContent = marker;
    (document.body ?? document.documentElement).appendChild(sentinel);
  }, api500MutationMarker);
}

async function finalizeApi500MutationObservation(page, contract, activeMutationOperator, tracker, assertions) {
  if (activeMutationOperator !== "api-500" || !(contract.selectors?.textMustNotExist ?? []).includes(api500MutationMarker)) return;
  if (!tracker.api500Intercepted) {
    const remainingContractTime = Math.max(0, tracker.contractDeadline - Date.now() - 1000);
    const remaining = Math.min(tracker.observationBudgetMs, remainingContractTime);
    if (remaining > 0) {
      await Promise.race([
        tracker.api500Interception,
        new Promise((resolve) => setTimeout(resolve, remaining))
      ]);
    }
  }
  if (!tracker.api500Intercepted) return;
  try {
    await appendApi500MutationSentinel(page);
  } catch {
    // The normal assertion below fails closed only when the exact sentinel can
    // be observed in the current page context.
  }
  await recordAssertion(assertions, "textMustNotExist", api500MutationMarker, async () => {
    await expect(page.getByText(api500MutationMarker, { exact: false }), \`Expected text to be absent: \${api500MutationMarker}\`).toHaveCount(0);
  });
}

function isExpectedConsoleError(contract, message) {
  return (contract.expectedConsoleErrors ?? []).some((pattern) => message.includes(pattern));
}

function sanitizeText(input) {
  let value = String(input);
  const keys = ["access_token", "id_token", "refresh_token", "authorization", "client_secret", "password", "secret", "token", "bearer", "cookie", "set-cookie", "code", "key"];
  for (const key of keys) {
    const escaped = key.replace(/[-/\\\\^$*+?.()|[\\]{}]/g, "\\\\$&");
    value = value.replace(new RegExp(\`(\${escaped})(\\\\s*[:=]\\\\s*)([^\\\\s,&;\\\\]\\\\)}]+)\`, "gi"), \`$1$2[REDACTED]\`);
    value = value.replace(new RegExp(\`(["']\${escaped}["']\\\\s*:\\\\s*["'])([^"']+)(["'])\`, "gi"), \`$1[REDACTED]$3\`);
    value = value.replace(new RegExp(\`([?&]\${escaped}=)([^&#\\\\s]+)\`, "gi"), \`$1[REDACTED]\`);
  }
  value = value.replace(/\\bBearer\\s+[A-Za-z0-9._~+/=-]+/gi, "Bearer [REDACTED]");
  value = value.replace(/\\bAuthorization:\\s*[^\\n\\r]+/gi, "Authorization: [REDACTED]");
  value = value.replace(/\\bCookie:\\s*[^\\n\\r]+/gi, "Cookie: [REDACTED]");
  value = value.replace(/\\bSet-Cookie:\\s*[^\\n\\r]+/gi, "Set-Cookie: [REDACTED]");
  return value;
}

function parseMutationOperators() {
  const raw = process.env.VISUAL_HIVE_MUTATION_OPERATORS;
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed.map((operator) => String(operator)).filter(Boolean);
  } catch {
    return raw.split(",").map((operator) => operator.trim()).filter(Boolean);
  }
  return [];
}

function parseMutationContractMatrix() {
  const raw = process.env.VISUAL_HIVE_MUTATION_MATRIX;
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};
    const matrix = {};
    for (const [operator, contractIds] of Object.entries(parsed)) {
      if (Array.isArray(contractIds)) {
        matrix[String(operator)] = contractIds.map((contractId) => String(contractId)).filter(Boolean);
      }
    }
    return matrix;
  } catch {
    return {};
  }
}

function mutationAppliesToContract(operator, contractId) {
  const contractIds = mutationContractMatrix[operator];
  return !Array.isArray(contractIds) || contractIds.length === 0 || contractIds.includes(contractId);
}

async function applyDomMutation(page, activeMutationOperator = mutationOperator) {
  if (activeMutationOperator === "hide-critical-button") {
    await page.addStyleTag({ content: "[data-testid='critical-action-button'] { display: none !important; }" });
  }
  if (activeMutationOperator === "remove-demo-badge") {
    await page.addStyleTag({ content: "[data-testid='demo-badge'] { display: none !important; }" });
  }
  if (activeMutationOperator === "mobile-overflow") {
    await page.addStyleTag({ content: "@media (max-width: 600px) { body::after { content: ''; display: block; width: 140vw; height: 1px; } }" });
  }
  if (activeMutationOperator === "force-login-on-demo") {
    await page.evaluate(() => {
      const forced = document.createElement("section");
      forced.setAttribute("data-testid", "login-page");
      forced.innerHTML = '<button data-testid="github-login-button">Continue with GitHub</button>';
      document.body.prepend(forced);
    });
  }
  if (activeMutationOperator === "route-guard-bypass") {
    await page.evaluate(() => {
      const protectedSurface = document.createElement("section");
      protectedSurface.setAttribute("data-testid", "protected-route");
      protectedSurface.setAttribute("role", "region");
      protectedSurface.setAttribute("aria-label", "Protected route bypass");
      protectedSurface.innerHTML = "<h2>Protected route bypass</h2><p>Cluster administration controls are visible without the expected guard.</p>";
      document.body.prepend(protectedSurface);
    });
  }
  if (activeMutationOperator === "hidden-error-banner") {
    await page.addStyleTag({
      content: "[data-testid='error-banner'], [role='alert'], .error-banner, .alert-error { display: none !important; visibility: hidden !important; }"
    });
  }
  if (activeMutationOperator === "broken-image") {
    await page.evaluate(() => {
      const images = Array.from(document.querySelectorAll("img"));
      for (const image of images) {
        image.setAttribute("data-visual-hive-original-src", image.getAttribute("src") || "");
        image.setAttribute("src", "/visual-hive-broken-image.png");
      }
      if (images.length === 0) {
        const broken = document.createElement("img");
        broken.setAttribute("data-testid", "visual-hive-broken-image");
        broken.setAttribute("alt", "Broken visual asset");
        broken.setAttribute("src", "/visual-hive-broken-image.png");
        broken.style.width = "96px";
        broken.style.height = "64px";
        broken.style.objectFit = "contain";
        document.body.prepend(broken);
      }
    });
  }
  if (activeMutationOperator === "removed-accessible-name") {
    await page.evaluate(() => {
      for (const element of Array.from(document.querySelectorAll("[aria-label], [alt], [title]"))) {
        element.removeAttribute("aria-label");
        element.removeAttribute("alt");
        element.removeAttribute("title");
      }
      for (const element of Array.from(document.querySelectorAll("button, [role='button'], a"))) {
        const text = element.textContent?.trim();
        if (text) {
          element.setAttribute("data-visual-hive-original-label", text);
          element.textContent = "";
        }
      }
    });
  }
  if (activeMutationOperator === "theme-token-drift") {
    await page.addStyleTag({
      content: ":root { --visual-hive-theme-drift: 1; } body { background: #fff7ed !important; color: #1f2937 !important; } button, [role='button'] { background: #b91c1c !important; color: #fff !important; } [class*='card'], article { border-color: #f97316 !important; box-shadow: inset 0 0 0 3px rgba(249, 115, 22, 0.25) !important; }"
    });
  }
  if (activeMutationOperator === "stale-loading-state") {
    await page.evaluate(() => {
      const loading = document.createElement("section");
      loading.setAttribute("data-testid", "loading-state");
      loading.setAttribute("aria-busy", "true");
      loading.setAttribute("role", "status");
      loading.textContent = "Loading dashboard data";
      loading.style.position = "fixed";
      loading.style.inset = "0";
      loading.style.zIndex = "2147483647";
      loading.style.display = "grid";
      loading.style.placeItems = "center";
      loading.style.background = "rgba(255, 255, 255, 0.92)";
      loading.style.color = "#111827";
      loading.style.font = "700 20px system-ui, sans-serif";
      document.body.append(loading);
    });
  }
}

async function verifyExecutionBinding() {
  if (verifiedExecutionBinding) return verifiedExecutionBinding;
  if (!/^[a-f0-9]{64}$/.test(executionNonce) || !executionPayload || !/^[a-f0-9]{64}$/.test(executionMac) || !executionBindingJson || !generatedSpecPath || !generatedConfigPath || !evidenceRoot) {
    throw new Error("Visual Hive Playwright execution binding is missing or malformed.");
  }
  const nonce = Buffer.from(executionNonce, "hex");
  const payload = Buffer.from(executionPayload, "base64");
  const actualMac = createHmac("sha256", nonce).update(payload).digest();
  const expectedMac = Buffer.from(executionMac, "hex");
  if (actualMac.length !== expectedMac.length || !timingSafeEqual(actualMac, expectedMac)) throw new Error("Visual Hive Playwright execution binding MAC is invalid.");
  const binding = JSON.parse(executionBindingJson);
  const payloadIdentity = JSON.parse(payload.toString("utf8"));
  const sha256 = (value) => createHash("sha256").update(value).digest("hex");
  const keys = Object.keys(binding).sort().join(",");
  if (keys !== "bindingMacSha256,generatedConfigSha256,generatedSpecSha256,nonceSha256,payloadSha256" || binding.nonceSha256 !== sha256(nonce) || binding.payloadSha256 !== sha256(payload) || binding.bindingMacSha256 !== executionMac) {
    throw new Error("Visual Hive Playwright persisted execution binding is invalid.");
  }
  const specBytes = await readFile(generatedSpecPath);
  const configBytes = await readFile(generatedConfigPath);
  if (binding.generatedSpecSha256 !== sha256(specBytes) || binding.generatedConfigSha256 !== sha256(configBytes) || payloadIdentity.generatedSpecSha256 !== binding.generatedSpecSha256 || payloadIdentity.generatedConfigSha256 !== binding.generatedConfigSha256) {
    throw new Error("Visual Hive generated Playwright spec or config does not match its execution binding.");
  }
  const expectedContracts = contracts.map((contract) => contract.id).sort();
  const expectedTargets = Object.keys(targets).sort();
  const expectedResultFiles = expectedContracts.map((contractId) => safeName(contractId) + ".json");
  if (JSON.stringify(payloadIdentity.expectedContracts) !== JSON.stringify(expectedContracts) || JSON.stringify(payloadIdentity.expectedTargets) !== JSON.stringify(expectedTargets) || JSON.stringify(payloadIdentity.expectedResultFiles) !== JSON.stringify(expectedResultFiles)) {
    throw new Error("Visual Hive Playwright execution inventory does not match its bound plan.");
  }
  if (!Object.prototype.hasOwnProperty.call(payloadIdentity, "repair") || (payloadIdentity.repair !== null && (typeof payloadIdentity.repair !== "object" || Array.isArray(payloadIdentity.repair)))) {
    throw new Error("Visual Hive Playwright execution mode is missing or malformed.");
  }
  exclusiveEvidenceWrites = payloadIdentity.repair !== null;
  const repositoryRoot = await realpath(rootDir);
  const boundEvidenceRoot = path.resolve(rootDir, String(payloadIdentity.evidenceRootPath || ""));
  const boundSpecPath = path.resolve(rootDir, String(payloadIdentity.generatedSpecPath || ""));
  const boundConfigPath = path.resolve(rootDir, String(payloadIdentity.generatedConfigPath || ""));
  const boundArtifactDirectory = path.resolve(rootDir, String(payloadIdentity.artifactDirectory || ""));
  const boundRuntimePath = payloadIdentity.runtimeSidecarPath ? path.resolve(rootDir, String(payloadIdentity.runtimeSidecarPath)) : "";
  if (!sameAbsolutePath(boundEvidenceRoot, evidenceRoot) || !sameAbsolutePath(boundSpecPath, generatedSpecPath) || !sameAbsolutePath(boundConfigPath, generatedConfigPath) || !sameAbsolutePath(boundArtifactDirectory, artifactDir) || !sameAbsolutePath(boundRuntimePath, runtimeSidecarPath)) {
    throw new Error("Visual Hive Playwright execution paths do not match their bound payload.");
  }
  const canonicalEvidenceRoot = await realpath(evidenceRoot);
  const evidenceRelative = path.relative(repositoryRoot, canonicalEvidenceRoot);
  if (evidenceRelative === ".." || evidenceRelative.startsWith(".." + path.sep) || path.isAbsolute(evidenceRelative) || !sameAbsolutePath(canonicalEvidenceRoot, boundEvidenceRoot)) {
    throw new Error("Visual Hive Playwright evidence root escaped or was redirected after authorization.");
  }
  verifiedEvidenceRoot = canonicalEvidenceRoot;
  verifiedExecutionBinding = Object.freeze(binding);
  return verifiedExecutionBinding;
}

function sameAbsolutePath(left, right) {
  if (!left && !right) return true;
  if (!left || !right) return false;
  const normalize = (value) => process.platform === "win32" ? path.resolve(value).toLowerCase() : path.resolve(value);
  return normalize(left) === normalize(right);
}

async function writeEvidenceFileExclusive(filePath, data, encoding) {
  if (!evidenceRoot) {
    await writeFile(filePath, data, encoding);
    return;
  }
  const root = await realpath(evidenceRoot);
  if (!verifiedEvidenceRoot || !sameAbsolutePath(root, verifiedEvidenceRoot)) throw new Error("Visual Hive evidence root changed after execution binding verification.");
  const absolute = path.resolve(filePath);
  const parent = path.dirname(absolute);
  const relativeParent = path.relative(root, parent);
  if (relativeParent === ".." || relativeParent.startsWith(".." + path.sep) || path.isAbsolute(relativeParent)) throw new Error("Visual Hive evidence write escaped its bound root.");
  let current = root;
  for (const segment of relativeParent.split(path.sep).filter(Boolean)) {
    current = path.join(current, segment);
    try {
      const entry = await lstat(current);
      if (!entry.isDirectory() || entry.isSymbolicLink()) throw new Error("Visual Hive evidence parent contains a linked or non-directory entry.");
    } catch (error) {
      if (!error || error.code !== "ENOENT") throw error;
      await mkdir(current);
      const created = await lstat(current);
      if (!created.isDirectory() || created.isSymbolicLink()) throw new Error("Visual Hive evidence parent creation was redirected.");
    }
  }
  const canonicalParent = await realpath(parent);
  const relativeCanonicalParent = path.relative(root, canonicalParent);
  if (relativeCanonicalParent === ".." || relativeCanonicalParent.startsWith(".." + path.sep) || path.isAbsolute(relativeCanonicalParent)) throw new Error("Visual Hive evidence parent resolved outside its bound root.");
  const noFollowFlag = process.platform === "win32" ? 0 : (constants.O_NOFOLLOW || 0);
  let handle;
  if (exclusiveEvidenceWrites) {
    handle = await open(absolute, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | noFollowFlag, 0o600);
  } else {
    try {
      handle = await open(absolute, constants.O_WRONLY | noFollowFlag);
      const existing = await handle.stat();
      if (!existing.isFile() || existing.nlink !== 1) throw new Error("Visual Hive reusable evidence destination is not one unlinked ordinary file.");
      await handle.truncate(0);
    } catch (error) {
      if (!error || error.code !== "ENOENT") throw error;
      handle = await open(absolute, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | noFollowFlag, 0o600);
    }
  }
  try {
    await handle.writeFile(data, encoding);
    await handle.sync();
  } finally {
    await handle.close();
  }
}

function joinUrl(base, route) {
  return new URL(route, base.endsWith("/") ? base : \`\${base}/\`).toString();
}

function safeName(value) {
  return String(value).replace(/[^a-z0-9_.-]+/gi, "-");
}

function artifactReference(filePath) {
  const relative = path.relative(rootDir, path.resolve(filePath));
  if (!relative || relative === ".." || relative.startsWith(".." + path.sep) || path.isAbsolute(relative)) throw new Error("Visual Hive artifact reference escaped the repository root.");
  return relative.split(path.sep).join("/");
}

function escapeRegExp(value) {
  return String(value).replace(/[|\\\\{}()[\\]^$+*?.]/g, "\\\\$&");
}
`;
}
