import path from "node:path";
import { writeText, type Plan, type VisualHiveConfig } from "@visual-hive/core";

export interface GenerateSpecOptions {
  config: VisualHiveConfig;
  plan: Plan;
  rootDir: string;
  outputDir?: string;
}

export interface GeneratedSpec {
  path: string;
  content: string;
}

export async function generatePlaywrightSpec(options: GenerateSpecOptions): Promise<GeneratedSpec> {
  const outputDir = options.outputDir ?? path.join(options.rootDir, ".visual-hive", "generated");
  const specPath = path.join(outputDir, "visual-hive.generated.spec.ts");
  const selectedIds = new Set(options.plan.items.map((item) => item.contractId));
  const contracts = options.config.contracts.filter((contract) => selectedIds.has(contract.id));
const content = buildSpecContent({
    rootDir: options.rootDir,
    contracts,
    targets: normalizeTargets(options.config.targets),
    viewports: options.config.viewports,
    visual: options.config.visual
  });
  await writeText(specPath, content);
  return { path: specPath, content };
}

function normalizeTargets(targets: VisualHiveConfig["targets"]): VisualHiveConfig["targets"] {
  const normalized: VisualHiveConfig["targets"] = {};
  for (const [id, target] of Object.entries(targets)) {
    if (target.url || (target.kind !== "commandGroup" && target.kind !== "protected")) {
      normalized[id] = target;
      continue;
    }
    normalized[id] = {
      ...target,
      url: target.services[0]?.url
    };
  }
  return normalized;
}

export function buildSpecContent(input: {
  rootDir: string;
  contracts: VisualHiveConfig["contracts"];
  targets: VisualHiveConfig["targets"];
  viewports: VisualHiveConfig["viewports"];
  visual: VisualHiveConfig["visual"];
}): string {
  return `// Generated by Visual Hive.
// Artifact: .visual-hive/generated/visual-hive.generated.spec.ts
// This file is intentionally readable so CI artifacts can be used for debugging.

import { test, expect } from "@playwright/test";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import pixelmatch from "pixelmatch";
import { PNG } from "pngjs";

// ---- Serialized Visual Hive plan inputs ----
const rootDir = ${JSON.stringify(input.rootDir)};
const contracts = ${JSON.stringify(input.contracts, null, 2)};
const targets = ${JSON.stringify(input.targets, null, 2)};
const viewports = ${JSON.stringify(input.viewports, null, 2)};
const visual = ${JSON.stringify(input.visual, null, 2)};
const snapshotDir = path.resolve(rootDir, visual.snapshotDir ?? ".visual-hive/snapshots");
const artifactDir = path.resolve(rootDir, visual.artifactDir ?? ".visual-hive/artifacts");
const visualHiveCi = process.env.VISUAL_HIVE_CI;
const ciMode = visualHiveCi === "true" ? true : visualHiveCi === "false" ? false : process.env.CI === "true";
const mutationOperator = process.env.VISUAL_HIVE_MUTATION_OPERATOR || "";

// ---- Contract execution ----
test.describe("visual-hive generated deterministic contracts", () => {
  for (const contract of contracts) {
    test(\`contract:\${contract.id}\`, async ({ page }) => {
      test.setTimeout(contract.timeoutMs ?? 30000);
      const target = targets[contract.target];
      const startedAt = Date.now();
      const selectorAssertions = [];
      const flowSteps = [];
      const screenshotAssertions = [];
      const consoleErrors = [];
      const pageErrors = [];
      const networkErrors = [];
      const artifacts = [];
      const errors = [];
      let contractStatus = "passed";

      page.on("console", (message) => {
        if (message.type() === "error" && !isExpectedConsoleError(contract, message.text())) {
          consoleErrors.push({ type: "console", message: sanitizeText(message.text()) });
        }
      });
      page.on("pageerror", (error) => {
        pageErrors.push({ type: "page", message: sanitizeText(error.message) });
      });
      page.on("response", (response) => {
        if (response.status() >= 400) {
          networkErrors.push({
            type: "network",
            url: sanitizeText(response.url()),
            status: response.status(),
            statusText: sanitizeText(response.statusText())
          });
        }
      });

      try {
        await applyRouteMutation(page);
        await page.addInitScript((operator) => {
          window.localStorage.setItem("visual-hive-mutation", operator);
        }, mutationOperator);

        const assertionRoute = contract.screenshots[0]?.route ?? "/";
        await page.setViewportSize(viewports.desktop ?? { width: 1440, height: 900 });
        await page.goto(joinUrl(target.url, assertionRoute), { waitUntil: "domcontentloaded" });
        await disableAnimations(page);
        await applyDomMutation(page);
        await applyWaits(page, contract, selectorAssertions);
        await assertSelectors(page, contract.selectors, selectorAssertions);
        await runFlowSteps(page, target, contract, flowSteps);

        for (const shot of contract.screenshots) {
          const viewport = viewports[shot.viewport];
          if (!viewport) {
            throw new Error(\`Unknown viewport "\${shot.viewport}" in screenshot "\${shot.name}"\`);
          }
          await page.setViewportSize(viewport);
          await page.goto(joinUrl(target.url, shot.route), { waitUntil: "domcontentloaded" });
          await disableAnimations(page);
          await applyDomMutation(page);
          await applyWaits(page, contract, selectorAssertions);
          await assertSelectors(page, contract.selectors, selectorAssertions);
          const assertion = await compareScreenshot(page, contract.id, shot, artifacts);
          screenshotAssertions.push(assertion);
          if (assertion.status === "created" && contractStatus !== "failed") {
            contractStatus = "created";
          }
          if (assertion.status === "failed" || assertion.status === "missing_baseline") {
            throw new Error(assertion.message ?? \`Screenshot assertion failed for \${contract.id}/\${shot.name}: diffRatio=\${assertion.actualDiffPixelRatio}\`);
          }
        }

        if (contract.failOnConsoleError && (consoleErrors.length > 0 || pageErrors.length > 0)) {
          throw new Error(\`Unexpected console/page errors in \${contract.id}\`);
        }
      } catch (error) {
        contractStatus = "failed";
        errors.push(sanitizeText(error instanceof Error ? error.message : String(error)));
        throw error;
      } finally {
        const resultPath = path.join(artifactDir, "results", \`\${safeName(contract.id)}.json\`);
        artifacts.push(resultPath);
        await mkdir(path.dirname(resultPath), { recursive: true });
        await writeFile(
          resultPath,
          JSON.stringify(
            {
              contractId: contract.id,
              targetId: contract.target,
              status: contractStatus,
              durationMs: Date.now() - startedAt,
              errors,
              artifacts,
              selectorAssertions,
              flowSteps,
              screenshotAssertions,
              consoleErrors,
              pageErrors,
              networkErrors,
              reproductionCommand: "visual-hive run --ci"
            },
            null,
            2
          ),
          "utf8"
        );
      }
    });
  }
});

async function runFlowSteps(page, target, contract, flowSteps) {
  for (const step of contract.steps ?? []) {
    const startedAt = Date.now();
    const result = {
      action: step.action,
      description: step.description,
      selector: step.selector,
      route: step.route,
      value: visibleStepValue(step),
      status: "passed",
      durationMs: 0
    };
    try {
      await executeFlowStep(page, target, step);
      result.durationMs = Date.now() - startedAt;
      flowSteps.push(result);
    } catch (error) {
      result.status = "failed";
      result.durationMs = Date.now() - startedAt;
      result.message = sanitizeText(error instanceof Error ? error.message : String(error));
      flowSteps.push(result);
      throw error;
    }
  }
}

async function executeFlowStep(page, target, step) {
  const timeout = step.timeoutMs ?? 5000;
  if (step.action === "goto") {
    await page.goto(joinUrl(target.url, step.route), { waitUntil: "domcontentloaded" });
    await disableAnimations(page);
    await applyDomMutation(page);
    return;
  }
  if (step.action === "click") {
    await page.locator(step.selector).first().click({ timeout });
    return;
  }
  if (step.action === "fill") {
    await page.locator(step.selector).first().fill(step.value ?? "", { timeout });
    return;
  }
  if (step.action === "press") {
    await page.locator(step.selector).first().press(step.key, { timeout });
    return;
  }
  if (step.action === "waitFor") {
    await page.locator(step.selector).first().waitFor({ state: step.state ?? "visible", timeout });
    return;
  }
  if (step.action === "assertVisible") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector to be visible: \${step.selector}\`).toBeVisible({ timeout });
    return;
  }
  if (step.action === "assertHidden") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector to be hidden: \${step.selector}\`).toBeHidden({ timeout });
    return;
  }
  if (step.action === "assertText") {
    await expect(page.locator(step.selector).first(), \`Expected flow selector text: \${step.selector}\`).toContainText(step.text ?? "", { timeout });
    return;
  }
  if (step.action === "assertUrl") {
    await expect(page, \`Expected URL to contain: \${step.value}\`).toHaveURL(new RegExp(escapeRegExp(step.value ?? "")), { timeout });
    return;
  }
  throw new Error(\`Unsupported Visual Hive flow step action: \${step.action}\`);
}

function visibleStepValue(step) {
  if (step.action === "fill") return step.value ? "[configured]" : undefined;
  return step.value ?? step.key ?? step.text;
}

async function applyWaits(page, contract, assertions) {
  for (const wait of contract.waitFor ?? []) {
    const assertion = { kind: "waitFor", value: wait.selector, status: "passed" };
    try {
      await page.locator(wait.selector).first().waitFor({ state: wait.state ?? "visible", timeout: wait.timeoutMs ?? 5000 });
      assertions.push(assertion);
    } catch (error) {
      assertion.status = "failed";
      assertion.message = error instanceof Error ? error.message : String(error);
      assertions.push(assertion);
      throw error;
    }
  }
}

async function assertSelectors(page, selectors = {}, assertions = []) {
  for (const selector of selectors.mustExist ?? []) {
    await recordAssertion(assertions, "mustExist", selector, async () => {
      await expect(page.locator(selector).first(), \`Expected selector to exist: \${selector}\`).toBeVisible();
    });
  }
  for (const selector of selectors.mustNotExist ?? []) {
    await recordAssertion(assertions, "mustNotExist", selector, async () => {
      await expect(page.locator(selector), \`Expected selector to be absent: \${selector}\`).toHaveCount(0);
    });
  }
  for (const text of selectors.textMustExist ?? []) {
    await recordAssertion(assertions, "textMustExist", text, async () => {
      await expect(page.getByText(text, { exact: false }).first(), \`Expected text to exist: \${text}\`).toBeVisible();
    });
  }
  for (const text of selectors.textMustNotExist ?? []) {
    await recordAssertion(assertions, "textMustNotExist", text, async () => {
      await expect(page.getByText(text, { exact: false }), \`Expected text to be absent: \${text}\`).toHaveCount(0);
    });
  }
}

async function recordAssertion(assertions, kind, value, fn) {
  const assertion = { kind, value, status: "passed" };
  try {
    await fn();
    assertions.push(assertion);
  } catch (error) {
    assertion.status = "failed";
    assertion.message = error instanceof Error ? error.message : String(error);
    assertions.push(assertion);
    throw error;
  }
}

// ---- Screenshot baseline handling ----
async function compareScreenshot(page, contractId, shot, artifacts) {
  const baselinePath = path.join(snapshotDir, \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  const actualPath = path.join(artifactDir, "screenshots", \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  const diffPath = path.join(artifactDir, "screenshots", \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.diff.png\`);
  await mkdir(path.dirname(baselinePath), { recursive: true });
  await mkdir(path.dirname(actualPath), { recursive: true });
  const mask = (shot.mask ?? []).map((selector) => page.locator(selector));
  const actual = await page.screenshot({
    fullPage: shot.fullPage ?? true,
    animations: "disabled",
    mask
  });
  artifacts.push(actualPath);

  const baseAssertion = {
    contractId,
    screenshotName: shot.name,
    name: shot.name,
    route: shot.route,
    viewport: shot.viewport,
    status: "passed",
    baselinePath,
    actualPath,
    maxDiffPixelRatio: visual.maxDiffPixelRatio,
    maxDiffPixels: visual.maxDiffPixels,
    actualDiffPixelRatio: 0,
    actualDiffPixels: 0,
    diffPixels: 0,
    totalPixels: 0
  };

  if (!existsSync(baselinePath) || visual.updateSnapshots) {
    if (!existsSync(baselinePath) && ciMode && visual.failOnMissingBaselineInCI && !visual.updateSnapshots) {
      await writeFile(actualPath, actual);
      return {
        ...baseAssertion,
        status: "missing_baseline",
        totalPixels: imagePixelCount(actual),
        diffPixels: imagePixelCount(actual),
        actualDiffPixels: imagePixelCount(actual),
        actualDiffPixelRatio: 1,
        message: \`Missing screenshot baseline in CI mode: \${baselinePath}. Run visual-hive locally without --ci to create the baseline, review it, and commit the approved snapshot if your project tracks baselines.\`
      };
    }
    await writeFile(baselinePath, actual);
    await writeFile(actualPath, actual);
    test.info().annotations.push({ type: "visual-hive", description: \`created baseline \${baselinePath}\` });
    return {
      ...baseAssertion,
      status: "created",
      totalPixels: imagePixelCount(actual)
    };
  }

  const baseline = await readFile(baselinePath);
  await writeFile(actualPath, actual);
  const diff = diffImages(baseline, actual);
  if (diff.diffPixels > 0) {
    await writeFile(diffPath, PNG.sync.write(diff.diffImage));
    artifacts.push(diffPath);
  }
  const failed =
    diff.actualDiffPixelRatio > visual.maxDiffPixelRatio ||
    (typeof visual.maxDiffPixels === "number" && diff.diffPixels > visual.maxDiffPixels);
  return {
    ...baseAssertion,
    status: failed ? "failed" : "passed",
    diffPath: diff.diffPixels > 0 ? diffPath : undefined,
    actualDiffPixelRatio: diff.actualDiffPixelRatio,
    actualDiffPixels: diff.diffPixels,
    diffPixels: diff.diffPixels,
    totalPixels: diff.totalPixels
  };
}

function diffImages(baselineBuffer, actualBuffer) {
  const baseline = PNG.sync.read(baselineBuffer);
  const actual = PNG.sync.read(actualBuffer);
  if (baseline.width !== actual.width || baseline.height !== actual.height) {
    const width = Math.max(baseline.width, actual.width);
    const height = Math.max(baseline.height, actual.height);
    return {
      diffImage: new PNG({ width, height }),
      diffPixels: width * height,
      totalPixels: width * height,
      actualDiffPixelRatio: 1
    };
  }
  const diffImage = new PNG({ width: baseline.width, height: baseline.height });
  const diffPixels = pixelmatch(baseline.data, actual.data, diffImage.data, baseline.width, baseline.height, { threshold: 0.1 });
  const totalPixels = baseline.width * baseline.height;
  return {
    diffImage,
    diffPixels,
    totalPixels,
    actualDiffPixelRatio: totalPixels === 0 ? 0 : diffPixels / totalPixels
  };
}

function imagePixelCount(buffer) {
  const image = PNG.sync.read(buffer);
  return image.width * image.height;
}

// ---- Determinism helpers ----
async function disableAnimations(page) {
  await page.addStyleTag({
    content: \`*, *::before, *::after {
      animation-duration: 0.001s !important;
      animation-delay: 0s !important;
      transition-duration: 0.001s !important;
      transition-delay: 0s !important;
      scroll-behavior: auto !important;
    }\`
  });
}

// ---- Mutation hooks ----
async function applyRouteMutation(page) {
  if (mutationOperator === "api-500") {
    await page.route("**/api/**", async (route) => {
      await route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: "visual-hive api-500 mutation" }) });
    });
  }
  if (mutationOperator === "empty-data") {
    await page.route("**/api/**", async (route) => {
      await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ items: [], message: "" }) });
    });
  }
  if (mutationOperator === "broken-image") {
    await page.route(/.*\\.(png|jpg|jpeg|gif|webp|svg)(\\?.*)?$/i, async (route) => {
      await route.fulfill({ status: 404, contentType: "text/plain", body: "visual-hive broken-image mutation" });
    });
  }
}

function isExpectedConsoleError(contract, message) {
  return (contract.expectedConsoleErrors ?? []).some((pattern) => message.includes(pattern));
}

function sanitizeText(input) {
  let value = String(input);
  const keys = ["access_token", "id_token", "refresh_token", "authorization", "client_secret", "password", "secret", "token", "bearer", "cookie", "set-cookie", "code", "key"];
  for (const key of keys) {
    const escaped = key.replace(/[-/\\\\^$*+?.()|[\\]{}]/g, "\\\\$&");
    value = value.replace(new RegExp(\`(\${escaped})(\\\\s*[:=]\\\\s*)([^\\\\s,&;\\\\]\\\\)}]+)\`, "gi"), \`$1$2[REDACTED]\`);
    value = value.replace(new RegExp(\`(["']\${escaped}["']\\\\s*:\\\\s*["'])([^"']+)(["'])\`, "gi"), \`$1[REDACTED]$3\`);
    value = value.replace(new RegExp(\`([?&]\${escaped}=)([^&#\\\\s]+)\`, "gi"), \`$1[REDACTED]\`);
  }
  value = value.replace(/\\bBearer\\s+[A-Za-z0-9._~+/=-]+/gi, "Bearer [REDACTED]");
  value = value.replace(/\\bAuthorization:\\s*[^\\n\\r]+/gi, "Authorization: [REDACTED]");
  value = value.replace(/\\bCookie:\\s*[^\\n\\r]+/gi, "Cookie: [REDACTED]");
  value = value.replace(/\\bSet-Cookie:\\s*[^\\n\\r]+/gi, "Set-Cookie: [REDACTED]");
  return value;
}

async function applyDomMutation(page) {
  if (mutationOperator === "hide-critical-button") {
    await page.addStyleTag({ content: "[data-testid='critical-action-button'] { display: none !important; }" });
  }
  if (mutationOperator === "remove-demo-badge") {
    await page.addStyleTag({ content: "[data-testid='demo-badge'] { display: none !important; }" });
  }
  if (mutationOperator === "mobile-overflow") {
    await page.addStyleTag({ content: "@media (max-width: 600px) { body::after { content: ''; display: block; width: 140vw; height: 1px; } }" });
  }
  if (mutationOperator === "force-login-on-demo") {
    await page.evaluate(() => {
      const forced = document.createElement("section");
      forced.setAttribute("data-testid", "login-page");
      forced.innerHTML = '<button data-testid="github-login-button">Continue with GitHub</button>';
      document.body.prepend(forced);
    });
  }
  if (mutationOperator === "route-guard-bypass") {
    await page.evaluate(() => {
      const protectedSurface = document.createElement("section");
      protectedSurface.setAttribute("data-testid", "protected-route");
      protectedSurface.setAttribute("role", "region");
      protectedSurface.setAttribute("aria-label", "Protected route bypass");
      protectedSurface.innerHTML = "<h2>Protected route bypass</h2><p>Cluster administration controls are visible without the expected guard.</p>";
      document.body.prepend(protectedSurface);
    });
  }
  if (mutationOperator === "hidden-error-banner") {
    await page.addStyleTag({
      content: "[data-testid='error-banner'], [role='alert'], .error-banner, .alert-error { display: none !important; visibility: hidden !important; }"
    });
  }
  if (mutationOperator === "broken-image") {
    await page.evaluate(() => {
      const images = Array.from(document.querySelectorAll("img"));
      for (const image of images) {
        image.setAttribute("data-visual-hive-original-src", image.getAttribute("src") || "");
        image.setAttribute("src", "/visual-hive-broken-image.png");
      }
      if (images.length === 0) {
        const broken = document.createElement("img");
        broken.setAttribute("data-testid", "visual-hive-broken-image");
        broken.setAttribute("alt", "Broken visual asset");
        broken.setAttribute("src", "/visual-hive-broken-image.png");
        broken.style.width = "96px";
        broken.style.height = "64px";
        broken.style.objectFit = "contain";
        document.body.prepend(broken);
      }
    });
  }
  if (mutationOperator === "removed-accessible-name") {
    await page.evaluate(() => {
      for (const element of Array.from(document.querySelectorAll("[aria-label], [alt], [title]"))) {
        element.removeAttribute("aria-label");
        element.removeAttribute("alt");
        element.removeAttribute("title");
      }
      for (const element of Array.from(document.querySelectorAll("button, [role='button'], a"))) {
        const text = element.textContent?.trim();
        if (text) {
          element.setAttribute("data-visual-hive-original-label", text);
          element.textContent = "";
        }
      }
    });
  }
  if (mutationOperator === "theme-token-drift") {
    await page.addStyleTag({
      content: ":root { --visual-hive-theme-drift: 1; } body { background: #fff7ed !important; color: #1f2937 !important; } button, [role='button'] { background: #b91c1c !important; color: #fff !important; } [class*='card'], article { border-color: #f97316 !important; box-shadow: inset 0 0 0 3px rgba(249, 115, 22, 0.25) !important; }"
    });
  }
  if (mutationOperator === "stale-loading-state") {
    await page.evaluate(() => {
      const loading = document.createElement("section");
      loading.setAttribute("data-testid", "loading-state");
      loading.setAttribute("aria-busy", "true");
      loading.setAttribute("role", "status");
      loading.textContent = "Loading dashboard data";
      loading.style.position = "fixed";
      loading.style.inset = "0";
      loading.style.zIndex = "2147483647";
      loading.style.display = "grid";
      loading.style.placeItems = "center";
      loading.style.background = "rgba(255, 255, 255, 0.92)";
      loading.style.color = "#111827";
      loading.style.font = "700 20px system-ui, sans-serif";
      document.body.append(loading);
    });
  }
}

function joinUrl(base, route) {
  return new URL(route, base.endsWith("/") ? base : \`\${base}/\`).toString();
}

function safeName(value) {
  return String(value).replace(/[^a-z0-9_.-]+/gi, "-");
}

function escapeRegExp(value) {
  return String(value).replace(/[|\\\\{}()[\\]^$+*?.]/g, "\\\\$&");
}
`;
}
