import path from "node:path";
import { writeText, type Plan, type VisualHiveConfig } from "@visual-hive/core";

export interface GenerateSpecOptions {
  config: VisualHiveConfig;
  plan: Plan;
  rootDir: string;
  outputDir?: string;
}

export interface GeneratedSpec {
  path: string;
  content: string;
}

export async function generatePlaywrightSpec(options: GenerateSpecOptions): Promise<GeneratedSpec> {
  const outputDir = options.outputDir ?? path.join(options.rootDir, ".visual-hive", "generated");
  const specPath = path.join(outputDir, "visual-hive.generated.spec.ts");
  const selectedIds = new Set(options.plan.items.map((item) => item.contractId));
  const contracts = options.config.contracts.filter((contract) => selectedIds.has(contract.id));
  const content = buildSpecContent({
    rootDir: options.rootDir,
    contracts,
    targets: options.config.targets,
    viewports: options.config.viewports
  });
  await writeText(specPath, content);
  return { path: specPath, content };
}

export function buildSpecContent(input: {
  rootDir: string;
  contracts: VisualHiveConfig["contracts"];
  targets: VisualHiveConfig["targets"];
  viewports: VisualHiveConfig["viewports"];
}): string {
  return `// Generated by Visual Hive.
// Artifact: .visual-hive/generated/visual-hive.generated.spec.ts
// This file is intentionally readable so CI artifacts can be used for debugging.

import { test, expect } from "@playwright/test";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

// ---- Serialized Visual Hive plan inputs ----
const rootDir = ${JSON.stringify(input.rootDir)};
const contracts = ${JSON.stringify(input.contracts, null, 2)};
const targets = ${JSON.stringify(input.targets, null, 2)};
const viewports = ${JSON.stringify(input.viewports, null, 2)};
const ciMode = process.env.VISUAL_HIVE_CI === "true" || process.env.CI === "true";
const mutationOperator = process.env.VISUAL_HIVE_MUTATION_OPERATOR || "";

// ---- Contract execution ----
test.describe("visual-hive generated deterministic contracts", () => {
  for (const contract of contracts) {
    test(\`contract:\${contract.id}\`, async ({ page }) => {
      const target = targets[contract.target];
      const consoleErrors = [];
      page.on("console", (message) => {
        if (message.type() === "error") {
          consoleErrors.push(message.text());
        }
      });

      await applyRouteMutation(page);
      await page.addInitScript((operator) => {
        window.localStorage.setItem("visual-hive-mutation", operator);
      }, mutationOperator);

      const assertionRoute = contract.screenshots[0]?.route ?? "/";
      await page.setViewportSize(viewports.desktop ?? { width: 1440, height: 900 });
      await page.goto(joinUrl(target.url, assertionRoute), { waitUntil: "networkidle" });
      await disableAnimations(page);
      await applyDomMutation(page);
      await assertSelectors(page, contract.selectors);

      for (const shot of contract.screenshots) {
        const viewport = viewports[shot.viewport];
        if (!viewport) {
          throw new Error(\`Unknown viewport "\${shot.viewport}" in screenshot "\${shot.name}"\`);
        }
        await page.setViewportSize(viewport);
        await page.goto(joinUrl(target.url, shot.route), { waitUntil: "networkidle" });
        await disableAnimations(page);
        await applyDomMutation(page);
        await assertSelectors(page, contract.selectors);
        await compareScreenshot(page, contract.id, shot);
      }

      if (consoleErrors.length > 0) {
        const consolePath = path.join(rootDir, ".visual-hive", "artifacts", \`\${safeName(contract.id)}-console-errors.json\`);
        await mkdir(path.dirname(consolePath), { recursive: true });
        await writeFile(consolePath, JSON.stringify(consoleErrors, null, 2), "utf8");
      }
    });
  }
});

async function assertSelectors(page, selectors = {}) {
  for (const selector of selectors.mustExist ?? []) {
    await expect(page.locator(selector).first(), \`Expected selector to exist: \${selector}\`).toBeVisible();
  }
  for (const selector of selectors.mustNotExist ?? []) {
    await expect(page.locator(selector), \`Expected selector to be absent: \${selector}\`).toHaveCount(0);
  }
  for (const text of selectors.textMustExist ?? []) {
    await expect(page.getByText(text, { exact: false }).first(), \`Expected text to exist: \${text}\`).toBeVisible();
  }
  for (const text of selectors.textMustNotExist ?? []) {
    await expect(page.getByText(text, { exact: false }), \`Expected text to be absent: \${text}\`).toHaveCount(0);
  }
}

// ---- Screenshot baseline handling ----
async function compareScreenshot(page, contractId, shot) {
  const baselinePath = path.join(rootDir, ".visual-hive", "snapshots", \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  const actualPath = path.join(rootDir, ".visual-hive", "artifacts", "screenshots", \`\${safeName(contractId)}__\${safeName(shot.name)}__\${safeName(shot.viewport)}.png\`);
  await mkdir(path.dirname(baselinePath), { recursive: true });
  await mkdir(path.dirname(actualPath), { recursive: true });
  const mask = (shot.mask ?? []).map((selector) => page.locator(selector));
  const actual = await page.screenshot({
    fullPage: shot.fullPage ?? true,
    animations: "disabled",
    mask
  });

  if (!existsSync(baselinePath)) {
    if (ciMode) {
      await writeFile(actualPath, actual);
      throw new Error(\`Missing screenshot baseline in CI mode: \${baselinePath}. Run visual-hive locally without --ci to create the baseline, review it, and commit the approved snapshot if your project tracks baselines.\`);
    }
    await writeFile(baselinePath, actual);
    await writeFile(actualPath, actual);
    test.info().annotations.push({ type: "visual-hive", description: \`created baseline \${baselinePath}\` });
    return;
  }

  const baseline = await readFile(baselinePath);
  await writeFile(actualPath, actual);
  expect(Buffer.compare(actual, baseline), \`Screenshot differs from baseline: \${baselinePath}\`).toBe(0);
}

// ---- Determinism helpers ----
async function disableAnimations(page) {
  await page.addStyleTag({
    content: \`*, *::before, *::after {
      animation-duration: 0.001s !important;
      animation-delay: 0s !important;
      transition-duration: 0.001s !important;
      transition-delay: 0s !important;
      scroll-behavior: auto !important;
    }\`
  });
}

// ---- Mutation hooks ----
async function applyRouteMutation(page) {
  if (mutationOperator === "api-500") {
    await page.route("**/api/**", async (route) => {
      await route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: "visual-hive api-500 mutation" }) });
    });
  }
  if (mutationOperator === "empty-data") {
    await page.route("**/api/**", async (route) => {
      await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ items: [], message: "" }) });
    });
  }
}

async function applyDomMutation(page) {
  if (mutationOperator === "hide-critical-button") {
    await page.addStyleTag({ content: "[data-testid='critical-action-button'] { display: none !important; }" });
  }
  if (mutationOperator === "remove-demo-badge") {
    await page.addStyleTag({ content: "[data-testid='demo-badge'] { display: none !important; }" });
  }
  if (mutationOperator === "mobile-overflow") {
    await page.addStyleTag({ content: "@media (max-width: 600px) { body::after { content: ''; display: block; width: 140vw; height: 1px; } }" });
  }
  if (mutationOperator === "force-login-on-demo") {
    await page.evaluate(() => {
      const forced = document.createElement("section");
      forced.setAttribute("data-testid", "login-page");
      forced.innerHTML = '<button data-testid="github-login-button">Continue with GitHub</button>';
      document.body.prepend(forced);
    });
  }
}

function joinUrl(base, route) {
  return new URL(route, base.endsWith("/") ? base : \`\${base}/\`).toString();
}

function safeName(value) {
  return String(value).replace(/[^a-z0-9_.-]+/gi, "-");
}
`;
}
